### ISSUE TITLE
Logitech g29 steering wheel

### ISSUE THREAD

**Issue by lepkyj** [Boomslangnz/FFBArcadePlugin#21]
I have been using the plugin for about a year with no issues. Out of nowhere it tells me my steering wheel does not support force feedback. Though it works on all other games and software. I did download the updated version and tried that one too but same thing. Any suggestions would be greatly appreciated.

**Comment by Boomslangnz** [comment]
Hi

Sorry ive been busy last few days.

Its most likely not loading the outputs which could be due to whatever mame and how you are loading games.

Come to teknoparrot discord if you can and i can give you more hands on help when you got time

**Comment by lepkyj** [comment]
No problem man. I am on discord for teknoparrot. I am only running into issues with Tekjnoparrot. What is your username on discord?

Thanks in advance

**Comment by saiyanvip** [comment]
> No problem man. I am on discord for teknoparrot. I am only running into issues with Tekjnoparrot. What is your username on discord?
> 
> Thanks in advance

if you have not found the solution and if I understand your problem, you should not use Logitech G HUB, I do not know if the problem comes from FFB or from the driver with logitech G hub, the G29 must be named in FFB "...G29..." and not something like "...HUB G29...".

It is necessary to completely uninstall GHUB, uninstall the drivers in device manager (check delete system drivers) and clean the windows registry of all keys related to G HUB or named GHUB.

Then install only Logitech Gaming Software, I have a doubt if the latest version is a problem or not, to test, otherwise look for an earlier version (which I preferred to do in doubt).

**Comment by Boomslangnz** [comment]
This issue was solved? It seems Logitech software has a habit of updating drivers etc and stopping FFB working so hopefully its been fixed by now

**Comment by lepkyj** [comment]
The same problem exists. It recognizes the wheel but when you test in in the GUI there is no response. 
Thanks for looking into to it.
    On Tuesday, March 7, 2023 at 06:41:35 AM EST, Michael Lepkyj ***@***.***> wrote:  
 
 I will take a look. I just have been copying the SDL2.dll from the last version that worked. It worked 90% of the time but there were a couple games the FFB would crash from it.
Thanks for the heads up, and thanks for your time.



On Mar 7, 2023, at 2:17 AM, Boomslangnz ***@***.***> wrote:


This issue was solved? It seems Logitech software has a habit of updating drivers etc and stopping FFB working so hopefully its been fixed by now

**Comment by Boomslangnz** [comment]
latest update should work fine on Logitech wheels and does here on latest ghub

Thanks
