### ISSUE TITLE
Keyboard stops responding shortly after start with Arcade64 + FFB plugin

### ISSUE THREAD

**Issue by zomgugoff** [Boomslangnz/FFBArcadePlugin#47]
Keyboard input stops working shortly after a game runs with Arcade64 (https://arcade.mameworld.info/) with FFB Plugin. I realize the plugin only names MAME for compatibility but I wouldn't think it should really cause this sort of thing to happen.

**Comment by baritonomarchetto** [comment]
I think this issue is related to what I experienced lately, so I am going to write here instead of opening a new issue.
What happens to me is that my hardware keyboard or any emulated keyboard (I am using H2Seq for sequential shifting) stops working after 20-30 seconds from running a game. Not only this happens to MAME games, but also Model2 emulator.
I made my homework and spotted the issue was generated from FFPlugin 2.0.0.5. 
Version 2.0.0.4 (and older) work 100% good with both emus. From 2.0.0.5 to the latest don't.

**Comment by Boomslangnz** [comment]
sorry for late reply, ok i will investigate, thanks

**Comment by Boomslangnz** [comment]
could you please test on latest FFB Plugin version and let me know if it still occurs? Flycast issue is resolved on latest update

**Comment by zomgugoff** [comment]
MAME ran for a couple minutes without losing keyboard input on the latest version. I will do an extended test before calling it 'fixed'.

**Comment by zomgugoff** [comment]
I'm not having any issues with keyboard input over long periods of time. Thanks for the fix!
